### ISSUE TITLE
AttributeError: 'KerasTensor' object has no attribute 'graph'

### ISSUE THREAD

**Issue by aakrandan** [Cuda-Chen/keras2onnx-example#7]
I followed through this tutorial, but while running convert_keras_to_onnx.py
script i am facing this error.

```
Traceback (most recent call last):
  File "convert_keras_to_onnx.py", line 9, in <module>
    onnx_model = keras2onnx.convert_keras(model, model.name)
  File "/Users/chethanshetty/Downloads/keras-onnx-master-2/keras2onnx/main.py", line 80, in convert_keras
    output_names, _process_initial_types(initial_types))
  File "/Users/chethanshetty/Downloads/keras-onnx-master-2/keras2onnx/_parser_tf.py", line 305, in build_layer_output_from_model
    graph = model.outputs[0].graph
AttributeError: 'KerasTensor' object has no attribute 'graph'
```

could you please help me resolve this issue?

**Comment by Cuda-Chen** [comment]
After some investigations, I found some newer dependencies will break this program.
Using the specific version of those dependencies solves this issue. and 
the problem was solve in this commit: https://github.com/Cuda-Chen/keras2onnx-example/commit/ad56c2108b3562fb0c484ab99c6b6eb0f4b65ed7

Feel free to re-open this issue if you still encounter problems.
